# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/', '/^SimpleSAML/', '__blackfire']
    tls:
        min_version: TLSv1.2
        strict_transport_security:
            enabled: true
            include_subdomains: false

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
